/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_udc_gac_hmusket_MusketCaller */

#ifndef _Included_es_udc_gac_hmusket_MusketCaller
#define _Included_es_udc_gac_hmusket_MusketCaller
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_udc_gac_hmusket_MusketCaller
 * Method:    callMusket
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_es_udc_gac_hmusket_MusketCaller_callMusket
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
